name: flame
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  elementary: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: 4.8.1
  retrofit: ^4.0.1
  dio: ^5.1.1
  auto_route: ^7.2.0
  provider: ^6.0.5
  google_fonts: ^4.0.4
  pretty_dio_logger: ^1.3.1
  logger: ^1.3.0
  flutter_svg: ^1.0.3
  decimal: ^2.3.2
  shared_preferences: ^2.1.1
  pinput: ^2.2.31
  markdown: ^7.1.0
  flutter_markdown: ^0.6.14
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  intl_utils: ^2.8.2
  flutter_rating_bar: ^4.0.1
  uuid: ^3.0.7
  flutter_masked_text2: ^0.9.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  retrofit_generator: ^6.0.0+3
  auto_route_generator: ^7.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/